FROM maven:3.6-jdk-11-slim as BUILD
COPY . /src
WORKDIR /src
RUN mvn install -DskipTests

FROM openjdk:11.0.1-jre-slim-stretch
EXPOSE 8080
WORKDIR /app
ARG JAR=spring-petclinic-2.7.0-SNAPSHOT.jar

COPY --from=BUILD /src/target/$JAR /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
CMD [OTEL_SERVICE_NAME=pet-clinic OTEL_EXPORTER=otlp_span OTEL_EXPORTER_OTLP_ENDPOINT=http://10.128.0.14:4317 OTEL_EXPORTER_OTLP_INSECURE=true  java -javaagent:./opentelemetry-javaagent.jar -jar target/*.jar --debug]
